### ISSUE TITLE
Upgrade to python 3.6

### ISSUE THREAD

**Issue by kisst** [nordcloud/cfn-encrypt#3]
In the template the Lambda functions are created with python 2.7 https://github.com/nordcloud/cfn-encrypt/blob/master/template.py#L225 etc, as the 2.x is getting close to end of life we should switch to 3.x

**Comment by artoliukkonen** [comment]
Just as a note; this has been fixed and can be closed. https://github.com/nordcloud/cfn-encrypt/commit/634a9f8d959e0a7eb0193070dd62d9db2bccba3a

**Comment by tdi** [comment]
👍
